version: "2"

services:
  admin:
      build: .
      volumes:
        - .:/app
        - /app/node_modules
      environment:
        - REACT_APP_API_URL=https://api.qarx.io
        - HTTPS=true
      ports:
        - "443:3000"

